### ISSUE TITLE
Exposure notifications shown as a "Silent Notification" in Android

### ISSUE THREAD

**Issue by emilykuret** [cds-snc/covid-shield-mobile#336]
Exposure notifications don't show up in the main notification section on the phone, they're in the "silent section". 

![Screenshot_20200630-155845](https://user-images.githubusercontent.com/55107923/86174347-7882a780-baef-11ea-99d1-8e58fb0543e2.png)

**Comment by henrytao-me** [comment]
Note: I didn't see same issue on my end. User can change notification priority if they want (see screenshots below). I suspect because the app notification is shown as NotificationCompat.PRIORITY_DEFAULT. It will be up to OS / default settings on device to group notification. This PR changes it to NotificationCompat.PRIORITY_MAX which makes sense because this is COVID-19 notification.

| ![image](https://user-images.githubusercontent.com/5274722/86808402-d27ff180-c048-11ea-89a4-1b4dc022731d.png)        | ![image](https://user-images.githubusercontent.com/5274722/86808407-d449b500-c048-11ea-8754-e63444ec92e8.png)           | ![image](https://user-images.githubusercontent.com/5274722/86808414-d57ae200-c048-11ea-9d04-4105fee7f926.png)  |
| ------------- |:-------------:| -----:|

@emilykuret

**Comment by timarney** [comment]
Merged - can re-open as needed.
