### ISSUE TITLE
Add screen for Android users with Location turned off

### ISSUE THREAD

**Issue by katewilhelm** [cds-snc/covid-shield-mobile#554]
If Location is turned off on an Android phone, [this documentation](https://support.google.com/android/answer/9930236?hl=en) says the app cannot work. We need to create a new Home screen to let people know the app is not working until they turn on Location. Right now, if you turn off Location after the app is installed, nothing happens in the app. 
<img width="525" alt="Screen Shot 2020-07-08 at 6 24 12 PM" src="https://user-images.githubusercontent.com/57191279/86976595-d430de80-c148-11ea-85c1-4535052c0f78.png">

**Comment by JuliannaR** [comment]
@smcmurtry this is a release blocker. Can we prioritize getting these screens added re: location services?

**Comment by smcmurtry** [comment]
> Right now, if you turn off Location after the app is installed, nothing happens in the app.

That is not a problem we are able to solve in the app. Because we don't have location permission, we don't know if it's on or off. It is up to android to solve this issue, this is what they're currently doing:

<img width="295" alt="Screen Shot 2020-07-08 at 9 42 10 PM" src="https://user-images.githubusercontent.com/5498428/86994559-ecfabd80-c163-11ea-91e9-712b9ba79a94.png">


If you set the app up, say yes to all the permissions, and later turn off location services, you will see this notification.

**Comment by smcmurtry** [comment]
The case we could potentially do something about is:
- a person has location services turned off
- they install our app
- they get to the EN framework permission popup and say continue
<img width="261" alt="Screen Shot 2020-07-08 at 9 52 35 PM" src="https://user-images.githubusercontent.com/5498428/86995079-5c24e180-c165-11ea-9db8-f43d401fa6b0.png">
- they are then shown the "enable location services" popup and they say cancel
<img width="254" alt="Screen Shot 2020-07-08 at 9 52 20 PM" src="https://user-images.githubusercontent.com/5498428/86995104-66df7680-c165-11ea-95c0-6c4bc0c68714.png">

They will then see the "exposure notifications disabled" screen:
<img width="348" alt="Screen Shot 2020-07-08 at 9 54 31 PM" src="https://user-images.githubusercontent.com/5498428/86995212-9db58c80-c165-11ea-93c3-522b4cdceb08.png">


We won't know if that is the path they took but we will know that they are android users with the EN framework off. So we could change the content those users see, but it would have to apply to people w/ location services on as well. And the button needs to stay the same, since that is the only flow available to our app to get them to enable location services.

**Comment by katewilhelm** [comment]
Thanks for that info. I've redesigned the disabled screen to add conditional text for Android users. French is still to come, but here's English 
<img width="203" alt="Screen Shot 2020-07-09 at 6 13 13 PM" src="https://user-images.githubusercontent.com/57191279/87096007-df9b0d00-c20f-11ea-9fc9-78a66ad1d580.png">
